stages:
  - test

stylecheck:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install pycodestyle
    - pycodestyle . --exclude=virtual

gitstats:
  stage:
