stages:
  - mirror
  - gitstats
  - test
  - finalize

github_mirror:
  stage: mirror
  tags:
    - linux-buildserver
  script:
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/html-index-generator.git master

generate gitstats:
  stage: gitstats
  tags:
    - linux-buildserver
  script:
    - gitstats . gitstats
    - rsync -av gitstats/ /var/www/gitstats.namibsun.net/public_html/gitstats/html-index-generator --delete-before

generate git_stats:
  stage: gitstats
  tags:
    - linux-buildserver
  script:
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/html-index-generator --delete-before

test_generating_index_for_coverage:
  stage: test
  tags:
    - linux-buildserver
  script:
    - python html-index-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
      -t template.html

test_generating_index_for_gitstats:
  stage: test
  tags:
    - linux-buildserver
  script:
    - python html-index-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html

test_generating_index_for_documentation:
  stage: test
  tags:
    - linux-buildserver
  script:
    - python html-index-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
      -t template.html -n Documentation -v

stylecheck:
  stage: test
  tags:
    - linux-buildserver
  script:
    - pep8 .

update_html_pages:
  stage: finalize
  when: always
  tags:
    - linux-buildserver
  script:
    - git clone https://gitlab.namibsun.net/namboy94/html-index-generator.git
    - cd html-index-generator
    - python html-index-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html
