stages:
  - mirror
  - test
  - gitstats
  - finalize

github_mirror:
  stage: mirror
  tags:
    - linux-buildserver
  script:
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/gitlab-release-uploader.git

create_gitlab_release:
  stage: test
  tags:
    - linux-buildserver
  only:
    - master
  script:
    - mkdir assets
    - echo "Hello World" > assets/testasset
    - python gitlab-release-uploader.py namboy94 gitlab-release-uploader
      $GITLAB_PERSONAL_ACCESS_TOKEN $CI_PIPELINE_ID "Test Release Notes"
      assets -u https://gitlab.namibsun.net -b master

checkstyle:
  stage: test
  tags:
    - linux-buildserver
  script:
    - pep8 .

generate gitstats:
  stage: gitstats
  tags:
    - linux-buildserver
  script:
    - gitstats . gitstats
    - rsync -av gitstats/ /var/www/gitstats.namibsun.net/public_html/gitstats/gitlab-release-uploader --delete-before

generate git_stats:
  stage: gitstats
  tags:
    - linux-buildserver
  script:
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/gitlab-release-uploader --delete-before

update_html_pages:
  stage: finalize
  when: always
  tags:
    - linux-buildserver
  script:
    - git clone https://gitlab.namibsun.net/namboy94/html-index-generator.git
    - cd html-index-generator
    - python html-index-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html
