stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/gitlab-build-scripts.git master -f

stylecheck:
  stage: test
  tags:
    - pycodestyle
  script:
    - pycodestyle .
