stages:
  - test
  - stats

stylecheck:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install pycodestyle
    - pycodestyle . --exclude=virtual

github_upload:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - github-release-upload namboy94 $GITHUB_AUTH_TOKEN $CI_COMMIT_SHA $CI_COMMIT_MESSAGE

gitlab_upload:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - gitlab-release-upload $GITLAB_AUTH_TOKEN $CI_COMMIT_SHA $CI_COMMIT_MESSAGE

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - gitstats-gen
