stages:
  - test
  - stats
  - release

stylecheck:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install pycodestyle
    - pycodestyle . --exclude=virtual

unittest:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - python-unittest

github_upload_test:
  stage: test
  only:
    - master
    - develop
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - mkdir -p assets && echo "TestAsset" > assets/test.txt
    - github-release-upload $(date +"%d.%m.%y.%H.%M.%S") "$(changelog-reader)" assets/* -b $CI_COMMIT_REF_NAME

gitlab_upload_test:
  stage: test
  only:
    - master
    - develop
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - mkdir -p assets && echo "TestAsset" > assets/test.txt
    - gitlab-release-upload $(date +"%d.%m.%y.%H.%M.%S") "$(changelog-reader)" assets/* -b $CI_COMMIT_REF_NAME

pypi_upload_test:
  stage: test
  only:
    - master
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - pypi-upload --test

release_upload:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - github-release-upload $(python setup.py -V) "$(changelog-reader)"
    - gitlab-release-upload $(python setup.py -V) "$(changelog-reader)"

pypi_upload:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - pypi-upload

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - gitstats-gen

docgen:
  stage: stats
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - sphinx-docgen