stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  script:
    - git push --mirror -f git@github.com:namboy94/gitlab-release-uploader.git

create_gitlab_release:
  stage: test
  only:
    - master
  script:
    - mkdir assets
    - echo "Hello World" > assets/testasset
    - python gitlab-release-uploader.py namboy94 gitlab-release-uploader
      $GITLAB_PERSONAL_ACCESS_TOKEN $CI_PIPELINE_ID "Test Release Notes"
      assets https://gitlab.namibsun.net master

checkstyle:
  stage: test
  script:
    - pep8 .
