stages:
  - test
  - stats

stylecheck:
  stage: test
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install pycodestyle
    - pycodestyle . --exclude=virtual

release_check:
  stage: test
  tags:
    - python3
  script:
    - echo $CI_SERVER_NAME
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_ID
    - echo $CI_PROJECT_NAMESPACE
    - echo $CI_PROJECT_URL

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && python setup.py install
    - gitstats-gen
