stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  script:
    - git push --mirror -f git@github.com:namboy94/github-release-uploader.git
    
create_github_release:
  stage: test
  script:
    - mkdir assets
    - echo "Hello World" > assets/testasset
    - python github-release-uploader.py namboy94 github-release-uploader 
      $GITHUB_PERSONAL_ACCESS_TOKEN $CI_PIPELINE_ID "Test Release Notes" 
      assets master

checkstyle:
  stage: test
  script:
    - pep8 .
