stages:
  - test
  - stats
  - release

default:
  image: namboy94/ci-docker-environment:latest
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - pip uninstall ci-scripts -y
    - python setup.py install

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags: [docker]
  script:
    - python-unittest

github_upload_test:
  stage: test
  only: [master, develop]
  tags: [docker]
  script:
    - mkdir -p assets && echo "TestAsset" > assets/test.txt
    - github-release-upload $(date +"%d.%m.%y.%H.%M.%S")
      "$(changelog-reader)" assets/* -b $CI_COMMIT_REF_NAME

gitlab_upload_test:
  stage: test
  only: [master, develop]
  tags: [docker]
  script:
    - mkdir -p assets && echo "TestAsset" > assets/test.txt
    - gitlab-release-upload $(date +"%d.%m.%y.%H.%M.%S")
      "$(changelog-reader)" assets/* -b $CI_COMMIT_REF_NAME

pypi_upload_test:
  stage: test
  only: [master, develop]
  tags: [docker]
  script:
    - echo $(date +"%d.%m.%y.%H.%M.%S") > version
    - pypi-upload --test

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(python setup.py -V) "$(changelog-reader)"
    - gitlab-release-upload $(python setup.py -V) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - pypi-upload

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script:
    - DEBIAN_FRONTEND=noninteractive apt install python3-setuptools latexmk texlive-latex-extra -y
    - python -V
    - sphinx-docgen
