stages:
  - mirror
  - test
  - gitstats
  - finalize

github_mirror:
  stage: mirror
  script:
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/changelog-reader.git master

create_gitlab_release_with_changelog:
  stage: test
  only:
    - master
  script:
    - git clone https://gitlab.namibsun.net/namboy94/gitlab-release-uploader.git
    - mkdir assets
    - python changelog-reader.py -c TESTLOG -d version
    - python gitlab-release-uploader/gitlab-release-uploader.py namboy94
      changelog-reader $GITLAB_PERSONAL_ACCESS_TOKEN $CI_PIPELINE_ID version
      assets -u https://gitlab.namibsun.net -b master
    - rm version
    - rmdir assets
    - rm -rf gitlab-release-uploader

checkstyle:
  stage: test
  script:
    - pep8 .

generate gitstats:
  stage: gitstats
  tags:
    - linux-buildserver
  script:
    - gitstats . gitstats
    - rsync -av gitstats/ /var/www/gitstats.namibsun.net/public_html/gitstats/changelog-reader --delete-before

generate git_stats:
  stage: gitstats
  tags:
    - linux-buildserver
  script:
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/changelog-reader --delete-before

update_html_pages:
  stage: finalize
  when: always
  tags:
    - linux-buildserver
  script:
    - git clone https://gitlab.namibsun.net/namboy94/html-index-generator.git
    - cd html-index-generator
    - python html-index-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
    - python html-index-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html
