stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  tags:
    - python
  script:
    - python src/github-mirror.py master

stylecheck:
  stage: test
  tags:
    - pycodestyle
  script:
    - pycodestyle .
